# Generated by Django 3.1.7 on 2021-04-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smart_meter_data',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
