# Generated by Django 3.1.7 on 2021-04-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_smart_meter_data_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smart_meter_data',
            options={'verbose_name_plural': 'Meter Data'},
        ),
    ]
